name: CI - Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t nexatech-web:ci .

      - name: Basic test (container run check)
        run: |
          docker run -d -p 8080:80 --name test-web nexatech-web:ci
          sleep 5
          curl -I http://localhost:8080 || exit 1

      - name: Cleanup
        run: |
          docker stop test-web
          docker rm test-web
